#!/bin/bash

DO_PUBLISH=0
DO_DEBUG=0
DO_LOCAL=0

while getopts "pdl" flag; do
case "$flag" in
    p) DO_PUBLISH=1;;
    d) DO_DEBUG=1;;
    l) DO_LOCAL=1;;
esac
done

MONTH=${@:$OPTIND:1}
YEAR=${@:$OPTIND+1:1}
PADDED_MONTH=`printf %02d $MONTH`
EXTRA_OPTS=" --noinclude-shiur-times --noinclude-chofesh-hagadol --noinclude-shiurim --noinclude-youth-minyan "

if [ $DO_DEBUG == 1 ] ; then
    perl -d $HOME/shul/shul-calendar/shul_cal2.cgi --month $MONTH --year $YEAR --fullpage $EXTRA_OPTS > $HOME/web/mamash.com/kat-calendars/${YEAR}_$PADDED_MONTH.html
else
    $HOME/shul/shul-calendar/shul_cal2.cgi --month $MONTH --year $YEAR --fullpage $EXTRA_OPTS > $HOME/web/mamash.com/kat-calendars/${YEAR}_$PADDED_MONTH.html
    if [ $DO_LOCAL == 0 ] ; then
        rsync  -avz $HOME/web/mamash.com m:web
    fi
fi

if [ $DO_PUBLISH == 1 ] ; then
    $HOME/shul/shul-calendar/shul_cal2.cgi --month $MONTH --year $YEAR  $EXTRA_OPTS > $HOME/web/kat.mamash.com/calendar/${YEAR}_$MONTH.html
    wkhtmltopdf $HOME/web/mamash.com/kat-calendars/${YEAR}_$PADDED_MONTH.html $HOME/web/kat.mamash.com/calendar/${YEAR}_$MONTH.pdf
    cp $HOME/web/kat.mamash.com/calendar/${YEAR}_$MONTH.pdf  $HOME/web/kat.mamash.com/calendar/current.pdf
    cp  $HOME/web/mamash.com/kat-calendars/${YEAR}_$PADDED_MONTH.html  $HOME/web/kat.mamash.com/calendar/current.html
    cp $HOME/web/kat.mamash.com/calendar/${YEAR}_$MONTH.html  $HOME/web/kat.mamash.com/calendar/current_include.html
    $HOME/shul/shul-calendar/shul_cal2.cgi --month $MONTH --year ${YEAR}  --fullpage $EXTRA_OPTS --noinclude-shiurim > $HOME/web/kat.mamash.com/calendar/current_simple.html
    wkhtmltopdf -O landscape  $HOME/web/kat.mamash.com/calendar/current_simple.html $HOME/web/kat.mamash.com/calendar/current_simple.pdf
    rsync  -avz $HOME/web/kat.mamash.com m:web
fi
